use master
go
ALTER DATABASE QUANLYTRANGTRAI SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
drop database QUANLYTRANGTRAI
go


CREATE DATABASE QUANLYTRANGTRAI;
GO
USE QUANLYTRANGTRAI;
GO

CREATE TABLE ANIMALS (
    ANIMALID INT IDENTITY(1,1) PRIMARY KEY,
    ANIMALTYPE NVARCHAR(50) NOT NULL,
    SOUND NVARCHAR(50) NOT NULL,
	CURRENT_COUNT INT DEFAULT 0,
    MILKPRODUCTION INT DEFAULT 0
);
GO
INSERT INTO ANIMALS (ANIMALTYPE, SOUND) VALUES ('Cow', 'Umbo');
INSERT INTO ANIMALS (ANIMALTYPE, SOUND) VALUES ('Sheep', 'CuuCuu');
INSERT INTO ANIMALS (ANIMALTYPE, SOUND) VALUES ('Goat', 'beeee');
GO
SELECT * FROM ANIMALS;
GO